[tool.black]
line-length = 79
target-version = ['py36', 'py37']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
  /(
      docs
    | node_modules
    | build*.py
    | media
    | storage
    | logs
    | site-static
    | static
    | \.git
    | \.npm
    | \.tox
  )/
  | src/olympia/wsgi\.py
  | src/.*/migrations/.*\.py
  | src/olympia/translations/tests/testapp/migrations/.*\.py
)
'''
